FROM node:18.5.0 as build-stage

WORKDIR /app

COPY ./frontend/package*.json /app/

RUN npm install

COPY ./frontend /app/

RUN npm run build

FROM nginx:1.23.0

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build-stage /app/build/ .

COPY nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]